- frontend/src/components/FRICalculator.vue
> updated validation to ccfri-estimator

- frontend/src/components/FRICalculator.vue
> Small UI update i missed.

- frontend/src/components/FRICalculator.vue
> removed v-dev and added min-width to the help icons

- .github/workflows/deploy-to-openshift-estimator-dev.yml
> updates to gitaction for estimator

- estimator-frontend/src/components/FRICalculator.vue
- frontend/src/components/FRICalculator.vue
> updated parent part time floor to

- estimator-frontend/src/components/FRICalculator.vue
> Last round of estimator UI udpates before prod.

- estimator-frontend/src/components/FRICalculator.vue
> Accidentally removed 'Parent fee frequency'.

- .github/workflows/deploy-to-openshift-estimator-test.yml
- .github/workflows/tag-create.git.and.imagestream.tag.yml
> updates to gitactions to tag and deploy to test

- .github/workflows/deploy-to-openshift-backend-dev.yml
- backend/src/app.js
- backend/src/config/index.js
- frontend-full-build/src/components/CcfriEstimator.vue
- frontend-full-build/src/router.js
- frontend/src/components/FRICalculator.vue
- tools/openshift/backend.dc.yaml
> Update jstorey's dev branch with main updates.

- backend/src/app.js
- backend/src/components/public.js
- backend/src/components/user.js
- backend/src/components/utils.js
- backend/src/config/index.js
- backend/src/routes/public.js
> initial D365 integration with facility search

- backend/src/components/utils.js
> added http utility methods for api operations

- backend/src/components/lookup.js
- backend/src/components/public.js
- backend/src/components/utils.js
- backend/src/routes/config.js
> added lookups

- backend/src/components/lookup.js
- backend/src/components/public.js
- backend/src/components/utils.js
- backend/src/routes/config.js
> Getting updates from main

- backend/src/app.js
- backend/src/components/lookup.js
- backend/src/components/organization.js
- backend/src/components/utils.js
- backend/src/routes/config.js
- backend/src/routes/organization.js
> created organization endpoints

- backend/src/components/organization.js
- backend/src/util/mapping/MappableObject.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/store/modules/organization.js
> Save org info

- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/FacilitySearch.vue
> Release estimator js

- frontend/src/components/FacilitySearch.vue
> Added no sonar tag because we don't want headers in <TH>.

- frontend/src/components/FacilitySearch.vue
> Fix to //NOSONAR tag in HTML.

- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/FacilitySearch.vue
- frontend/src/components/Header.vue
> Estimator bug fixes from QA.

- frontend/src/components/FacilitySearch.vue
> Fixing typos.

- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/FacilitySearch.vue
> Latest estimator changes.

- frontend/src/components/CcfriEstimator.vue
> Estimator fixes.

- frontend/src/components/CcfriEstimator.vue
> Estimator: fixed feedback button senario.

- backend/src/components/facility.js
- backend/src/components/organization.js
- backend/src/util/mapping/Mappings.js
- frontend/src/store/modules/auth.js
- frontend/src/store/modules/facility.js
- frontend/src/store/modules/organization.js
> updates to create facility

- backend/src/components/facility.js
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
> incorporated ccof base funding into nav bar

- .github/workflows/deploy-to-openshift-frontend-test.yml
- frontend/public/index.html
- frontend/public/js/config/snowplow.js
- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/FacilitySearch.vue
- frontend/src/components/Header.vue
> Release estimator

- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/FacilitySearch.vue
- frontend/src/components/Header.vue
> Release estimator js2

- frontend/src/components/eceweApplication/DocumentUpload.vue
- frontend/src/components/eceweApplication/Eligibility.vue
- frontend/src/components/eceweApplication/Facilities.vue
- frontend/src/components/eceweApplication/Summary.vue
- frontend/src/router.js
- frontend/src/store/index.js
- frontend/src/store/modules/eceweApp.js
- frontend/src/utils/constants.js
> ECEWE intake 1st check-in.

- backend/src/components/facility.js
- backend/src/components/funding.js
- backend/src/components/organization.js
- backend/src/routes/funding.js
- backend/src/util/mapping/MappableObject.js
- frontend/src/components/ccofApplication/CcofApplicationTypeSelector.vue
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
- frontend/src/store/modules/app.js
- frontend/src/store/modules/auth.js
- frontend/src/store/modules/ccof/group/groupFundingStore.js
- frontend/src/store/modules/facility.js
- frontend/src/store/modules/organization.js
> integration with navbar and funding

- frontend/src/components/LandingPage.vue
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
- frontend/src/store/modules/app.js
> cleaned up navigation

- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/util/NavBar.vue
> intermim checkin

- backend/src/util/mapping/Mappings.js
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
> incorporating CCFRI to navbar

- backend/src/components/user.js
- frontend/src/App.vue
> intermittent checkin

- frontend/src/components/util/NavBar.vue
> updates to navbar

- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
> added auth.userProfile to navBar, added guids for ECEWE navigation

- backend/src/components/user.js
> fixed a bug on userprofile for ccfri status

- backend/src/components/lookup.js
- backend/src/components/organization.js
- backend/src/components/user.js
- backend/src/routes/organization.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/LandingPage.vue
- frontend/src/store/modules/app.js
- frontend/src/store/modules/organization.js
> added program year lookup, enabled add new user functionality

- backend/src/components/lookup.js
- frontend/src/components/Impersonate.vue
> debugging on dev!

- frontend/src/common/apiService.js
> more debugging in dev

- backend/src/components/user.js
- frontend/src/components/LandingPage.vue
> fixed bug where user cannot log in when idir has no email

- backend/src/components/user.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/modules/app.js
- frontend/src/store/modules/auth.js
- frontend/src/store/modules/organization.js
> Merging main updates into ECEWE dev branch.

- frontend/src/components/eceweApplication/Eligibility.vue
- frontend/src/components/eceweApplication/Facilities.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
- frontend/src/store/modules/eceweApp.js
> Merging ECEWE dev branch into main after code QA.

- backend/src/app.js
- backend/src/components/licenseUpload.js
- backend/src/components/utils.js
- backend/src/routes/licenseUpload.js
- frontend/package.json
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
- frontend/src/store/index.js
- frontend/src/store/modules/app.js
- frontend/src/store/modules/licenseUpload.js
- frontend/src/utils/common.js
- frontend/src/utils/constants.js
> CCFRI-535 | MyCSS - Create file upload for facility licenses |

- backend/src/components/user.js
- frontend/src/store/modules/rfiApp.js
- frontend/src/utils/constants.js
> fixes to merge issues

- backend/src/components/user.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/util/NavBar.vue
> updated to use new providerprofile

- backend/src/util/mapping/Mappings.js
- frontend/src/components/util/NavBar.vue
> updates to provider profile.  reverted some navBar ui changes

- backend/src/components/application.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/utils/constants.js
> Summary and declaration refinements.

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/modules/summaryDeclaration.js
> Declaration code improvements.

- frontend/src/components/LandingPage.vue
- frontend/src/components/guiComponents/SmallCard.vue
> Update Dashboard page: CCOF card + Add Optin options

- backend/src/components/facility.js
- backend/src/components/funding.js
- backend/src/components/lookup.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/ccofApplication/CcofApplicationTypeSelector.vue
- frontend/src/components/ccofApplication/family/Eligibility.vue
- frontend/src/components/ccofApplication/family/FamilyFunding.vue
- frontend/src/components/ccofApplication/family/FamilyOrganization.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/mixins/fundMixing.js
- frontend/src/store/modules/ccof/organization.js
- frontend/src/store/modules/licenseUpload.js
- frontend/src/store/modules/summaryDeclaration.js
> updates to family organization with navbar changes

- frontend/src/components/MessagesPage.vue
> Update Message Page to fit within screen

- frontend/src/components/LandingPage.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
- frontend/src/components/ccofApplication/RenewOrganization.vue
- frontend/src/components/ccofApplication/family/Eligibility.vue
- frontend/src/components/ccofApplication/family/FamilyFunding.vue
- frontend/src/components/ccofApplication/family/FamilyOrganization.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/mixins/fundMixing.js
- frontend/src/mixins/organizationMixin.js
- frontend/src/router.js
- frontend/src/store/modules/ccfriApp.js
- frontend/src/store/modules/ccof/facility.js
- frontend/src/store/modules/ccof/funding.js
- frontend/src/store/modules/ccof/organization.js
- frontend/src/store/modules/summaryDeclaration.js
> fixes to integation and navigation for family and renewals

- frontend/src/components/LandingPage.vue
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
> updates for renewing existing renewals

- test/package-lock.json
- test/src/data/test1-funding.txt
- test/src/pageObjects/PageFunding.js
- test/src/testCases/update-funding.js
- test/src/utils/selectors.js
> Test Cafe Intake Scripts (Funding)

- backend/src/components/application.js
- backend/src/components/facility.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/modules/ccfriApp.js
> 0108 dev jbeckett - CCFRI bug fixes 

- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/modules/app.js
- frontend/src/store/modules/eceweApp.js
> ECEWE updates: refactoring, fixing state management, navBar complete for ecewe

- frontend/src/components/SummaryDeclaration.vue
> Declaration screen: fixed isRenewal comes from application not app

- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
> Upload screens: refined skeleton loader, and isProcessing on all buttons

- backend/src/components/application.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/store/modules/summaryDeclaration.js
> Submission: updated with relock functionality

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
> ECEWE, Declartion: added renewal header text, removed loading buttons

- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
> UI loading and saving consistency

- backend/src/components/facility.js
- backend/src/components/rfiApplication.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/mixins/fundMixing.js
- frontend/src/mixins/organizationMixin.js
- frontend/src/router.js
- frontend/src/store/modules/app.js
- frontend/src/store/modules/ccfriApp.js
> bug fixes after integration

- frontend/src/components/LandingPage.vue
> Fixing unlock bug for isRenewEnabled()

- frontend/src/components/RFI/NMF.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/utils/common.js
> Update NMF UI

- backend/src/components/rfiApplication.js
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/mixins/fundMixing.js
- frontend/src/mixins/organizationMixin.js
- frontend/src/store/index.js
- frontend/src/store/modules/app.js
- frontend/src/store/modules/ccof/organization.js
> added navbar routes, added hasRFI flag

- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
> File upload type issue

- backend/src/util/mapping/Mappings.js
> 20230117 am dev

- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/modules/ccfriApp.js
> updates to RFI logic

- backend/src/components/rfiApplication.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/modules/rfiApp.js
> Dev jbeckett 0117 RFI only saves when changed/ indigenous Service integration 

- frontend/src/mixins/facilityMixin.js
> fixed the facility postal code bug

- frontend/src/components/util/NavBar.vue
> prevent users from accessing accessing declaration if nto complete

- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/store/modules/eceweApp.js
> ECEWE: UI fixes and fix on unreported bug related to auto opt out.

- backend/src/components/facility.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/ccofApplication/family/FamilyFunding.vue
- frontend/src/mixins/fundMixing.js
- frontend/src/utils/rules.js
> 230119 am dev

- backend/src/components/facility.js
- backend/src/components/funding.js
- backend/src/components/rfiApplication.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccofApplication/family/FamilyFunding.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/mixins/fundMixing.js
- frontend/src/store/modules/app.js
- frontend/src/store/modules/ccof/funding.js
- frontend/src/store/modules/rfiApp.js
> updates to rfi

- backend/src/components/nmfApplication.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/guiComponents/SmallCard.vue
- frontend/src/store/modules/auth.js
- frontend/src/store/modules/ccof/organization.js
- frontend/src/store/modules/nmfApp.js
> Update Dashboard and fix NMF bug

- frontend/src/components/LandingPage.vue
> Dashboard: fix View Application button

- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
> Dev jbeckett 0120- RFI lock/unlock, skeleton loader, additional form validation around number fields

- frontend/src/components/LandingPage.vue
- frontend/src/components/Login.vue
- frontend/src/components/MinistryLogin.vue
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/ccofApplication/RenewOrganization.vue
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/guiComponents/SmallCard.vue
> Add disable logic to Application Confirmation page, Update wording in multiple pages, Update CCOF Funding Routes in Dashboard

- backend/src/components/facility.js
- frontend/src/components/Login.vue
- frontend/src/components/MessagesPage.vue
- frontend/src/components/MinistryLogin.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
> working changes, fixed a bug for childcaretypes

- frontend/src/components/SummaryDeclaration.vue
> updates to wording

- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
> Fix bug CCFRI-1195 with File upload

- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> Dev jbeckett 0120 bug fix for AddNewFees when switching between facilities 

- backend/src/components/rfiApplication.js
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> bug fixing!

- frontend/src/components/Login.vue
> Fix issue with v-card-title word wrapping

- frontend/src/components/RFI/RFILanding.vue
> Text only changes and one field repositioning as requested.

- frontend/src/components/Login.vue
- frontend/src/components/MinistryLogin.vue
- frontend/src/components/RFI/NMF.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/vue.config.js
> Update RFI wording (CCFRI-1212, CCFRI-1213, CCFRI-1214, CCFRI-1268), Login header image (CCFRI-1202)

- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
- frontend/src/store/modules/app.js
> updates to RFI screens

- backend/src/components/user.js
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> fixed provider profile bug

- frontend/src/components/RFI/NMF.vue
- frontend/src/components/RFI/RFILanding.vue
> RFI: adding links to instances of 'Funding Guidelines'.

- frontend/src/components/LandingPage.vue
- frontend/src/store/modules/ccof/organization.js
> Add a logic check to create the NEW Application in the Future Program and Wording change in CCFRI-1288

- frontend/src/components/LandingPage.vue
- frontend/src/store/modules/message.js
> Fix Update Your PCF button and Message screen bugs

- frontend/src/components/Login.vue
> CCFRI-1315 - Add FOIPPA note to Login Page

- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
MyCCS - Licence Upload Section Wording
> CCFRI-1282

- frontend/src/components/Login.vue
> CCFRI-1315 - Add FOIPPA note to Login Page - wording changes

- backend/src/components/application.js
- backend/src/util/mapping/Mappings.js
> added applicable selector to backend

- frontend/src/components/eceweApplication/EceweEligibility.vue
> CCFRI-1283 - Add new question for applicable sector to ECEWE eligibility

- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
> Develop vietle 3

- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
> wording change on existing fees

- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> wording change on AddNewFees

- backend/src/components/application.js
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/modules/app.js
- frontend/src/store/modules/ccfriApp.js
- frontend/src/store/modules/eceweApp.js
> Dev jbeckett 0123 - bug tickets 1242, 1253, 1321

- backend/src/components/lookup.js
- backend/src/routes/public.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/Login.vue
- frontend/src/utils/constants.js
> Added System Notification to Login Page

- frontend/src/components/SummaryDeclaration.vue
> updated layout and wording for declaration page

- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
> CCFRI-1380 - pagination change

- frontend/src/components/ccofApplication/RenewOrganization.vue
- frontend/src/store/modules/nmfApp.js
> updates to renewal screen to prevent multple clicks

- backend/src/components/user.js
> fixed email quote bug

- frontend/src/components/RFI/RFILanding.vue
> removed an extra texbox on RFI

- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> added are prev years fee correct on Read Only to AddNewFees

- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
> bug fix: JIRA-1435

- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> Dev jbeckett feb1 bug ticket 1215 

- backend/src/components/rfiApplication.js
> Dev jbeckett feb9

- backend/src/util/mapping/Mappings.js
> swapped 2 fields on ServiceExpansion mapping

- backend/src/components/rfiApplication.js
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> fixed timezone issue on create RFI

- backend/src/util/mapping/Mappings.js
- frontend/src/components/Header.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/store/modules/auth.js
- frontend/src/store/modules/ccof/organization.js
> funding agreement number

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccofApplication/RenewOrganization.vue
- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
> Wording change for CCFRI-1287, CCFRI-1277, CCFRI-1189, CCFRI-1185

- frontend/src/components/SummaryDeclaration.vue
> updates to remove certification checkbox when unlocked

- backend/src/components/application.js
> updated closure dates to use pst timezone

- frontend/public/styles/common.css
- frontend/src/components/RFI/RFILanding.vue
> Next button update

- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
> Dev jbeckett fix ccfri next btn

- frontend/package.json
- frontend/src/components/util/NavBar.vue
- frontend/src/store/modules/ccfriApp.js
- frontend/tests/unit/store/ccfriApp.spec.js
> Release 1.6.9a ccfri 1613

- frontend/src/components/LandingPage.vue
> CCFRI-1558 - Update the text for Submitted status

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/summary/group/FacilityInformationSummary.vue
> fixed bug where facility information was incorrectly showing as incomplete

- frontend/src/components/ModalIdle.vue
> update timeout to 120 secons

- backend/src/components/public.js
> added order by in query for ccfri estimator

- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> NavButton - Update the AddNewFees disable logic for Next button

- frontend/src/components/summary/group/CCFRISummary.vue
- frontend/src/components/summary/group/CCOFSummary.vue
- frontend/src/components/summary/group/CCOFSummaryFamily.vue
- frontend/src/components/summary/group/ECEWESummary.vue
- frontend/src/components/summary/group/FacilityInformationSummary.vue
- frontend/src/components/summary/group/NMFSummary.vue
- frontend/src/components/summary/group/OrganizationSummary.vue
- frontend/src/components/summary/group/RFISummary.vue
- frontend/src/components/summary/group/UploadedDocumentsSummary.vue
- frontend/src/store/modules/summaryDeclaration.js
> CCFRI 1724 bug fix, change a tags to use router-link

- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
> bug fix 1273 remove FY from for loop

- frontend/src/components/summary/group/ECEWESummary.vue
> bug fix ccfri 1736 cannot submit when ecewe opt out

- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
> wording and regex update for bug 1273

- frontend/src/components/Logout.vue
- frontend/src/components/SessionExpired.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/modules/app.js
> Navbar changes

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/summary/group/CCOFSummaryFamily.vue
- frontend/src/components/summary/group/OrganizationSummary.vue
> Jb 1724 more bug fixes

- frontend/src/components/ccofApplication/family/FamilyFunding.vue
Added the required tag to Family Funding Page, without this it will cause the CCFRI Add Fees screen to show no fees ( since there are no child care categories associated with that facility )
Bug fix (non-breaking change which fixes an issue
> MyCCS - Dev - Family Funding required tag missing

- backend/src/components/lookup.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/ccofApplication/RenewOrganization.vue
- frontend/src/store/modules/app.js
- frontend/src/store/modules/ccof/organization.js
> updates to allow renewals without future program years

- frontend/src/components/SummaryDeclaration.vue
> fixed grey box css thing

- frontend/src/components/ccofApplication/group/FundAmount.vue
1077 - This fixes the issue where preschool shouldn't be shown unless the number of preschools is greater than 0
1079 -Ungroup the "Group Child Care (School Age Care on School Grounds)" and "Is the facility located on school property?" questions
1816 -Language update to “30 Months to School Age”
1153 - Only show if Group Child Care is greater than 0 
CCFRI-1077
CCFRI-1079
CCFRI-1816
CCFRI-1153
> CCFRI-1077, CCFRI-1079, CCFRI-1816, CCFRI-1153 

- frontend/src/components/SummaryDeclaration.vue
> Jb ccfri 1751 Dec A / B unlock for new applications

- frontend/src/components/ModalIdle.vue
- frontend/src/store/modules/app.js
> updated to handle vue.js timer when in background

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/summary/group/ECEWESummary.vue
- frontend/src/components/summary/group/OrganizationSummary.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/mixins/organizationMixin.js
> Rl ccfri 1261

- backend/src/util/mapping/Mappings.js
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccofApplication/family/FamilyFunding.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/summary/group/CCOFSummary.vue
- frontend/src/components/summary/group/CCOFSummaryFamily.vue
- frontend/src/store/modules/ccfriApp.js
> CCFRI-1734

- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/summary/group/CCOFSummaryFamily.vue
- frontend/src/components/summary/group/FacilityInformationSummary.vue
> updates to summary declaration for validation

- frontend/src/components/summary/group/ECEWESummary.vue
> ECEWE Summary Declaration - Add missing confirm text to ECEWE summary + update UI

- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/summary/group/CCOFSummary.vue
> added missing schoolgrounds question to Summary Declaration

- frontend/src/components/LandingPage.vue
> LandingPage: fix bug - user can renew application outside intake time

- frontend/src/components/requestChanges/ChangeNotificationForm.vue
- frontend/src/components/requestChanges/ReportChanges.vue
> added in wording for report change page

- frontend/src/components/CcfriEstimator.vue
> removed care types that don't exist from estimator

- backend/src/components/public.js
> only return the latest approved fees

- backend/src/components/application.js
- backend/src/components/facility.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/router.js
- frontend/src/store/modules/app.js
- frontend/src/store/modules/ccof/facility.js
- frontend/src/store/modules/reportChanges.js
- frontend/src/utils/common.js
- frontend/src/utils/constants.js
> Report changes jb

- backend/src/util/mapping/Mappings.js
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/requestChanges/ChangeFileUpload.vue
- frontend/src/components/requestChanges/ChangeNotificationForm.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/router.js
- frontend/src/store/modules/application.js
- frontend/src/store/modules/ccof/facility.js
- frontend/src/store/modules/navBar.js
- frontend/src/store/modules/reportChanges.js
> integration changes for report changes

- backend/src/components/facility.js
- backend/src/routes/facility.js
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/store/modules/app.js
- frontend/src/store/modules/ccof/facility.js
- frontend/src/store/modules/ccof/funding.js
> Ccfri 1093

- frontend/src/components/CcfriEstimator.vue
> css changes to make button and text align nice with flexbox

- backend/src/components/application.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/router.js
- frontend/src/store/modules/ccof/facility.js
- frontend/src/store/modules/eceweApp.js
- frontend/src/utils/common.js
> Report Change ECEWE + add changeActionId to ReportChanges to avoid adding extra CR issue

- frontend/src/components/requestChanges/ChangeFileUpload.vue
> fixed a bug I introduced for report changes, other changes

- frontend/src/components/SupportingDocumentUpload.vue
> Jb 1846-  Supporting Documents uploaded files on wrong lines when adding new documents

- backend/src/components/lookup.js
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/summary/group/ECEWESummary.vue
Change in language and style on CCOF application. 
Organization (CCFRI-1840 1 Organization.png)
a.	Insert title above Organization Contact Name field: “Contact Information”
b.	Make “Type of Organization” the title for section (same formatting as “Organization Mailing Address” above)
b1.   Relocate “Incorporation Number (as it appears in BC Corporate Registry) directly below “Legal Name”
Funding (CCFRI1840 2 Funding.png)
c.	Missing word. Should be “Maximum number of weeks per year you provide child care”
d.	Facility hours of operation section should be immediately below “Maximum number of days per week you provide child care”
e.	In Facility hours of operation, “from” and “to” should be all lower case
f.	In Maximum Number School Age, fix capitalization in brackets. Should be “(School Age / …
> Ccfri 1840

- frontend/src/components/LandingPage.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/store/modules/eceweApp.js
- frontend/src/utils/common.js
> P2 bug fix CCFRI-2073 and CCFRI-2088

- backend/src/routes/auth.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/store/modules/eceweApp.js
- frontend/src/utils/common.js
> Estimator v2

- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/summary/group/CCFRISummary.vue
- frontend/src/components/summary/group/ECEWESummary.vue
- frontend/src/utils/common.js
> Report changes rl

- frontend/src/router.js
- frontend/src/store/modules/app.js
> Fixed subtitle banner for New App

- backend/src/components/user.js
- backend/src/util/mapping/ChangeRequestMappings.js
> added additional fields to userprofile for change request

- backend/src/components/application.js
- backend/src/components/licenseUpload.js
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
- frontend/src/store/modules/licenseUpload.js
- frontend/src/store/modules/navBar.js
- frontend/src/store/modules/reportChanges.js
> updates to navbar for change requests to handle checkmarks

- backend/src/util/mapping/ChangeRequestMappings.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/requestChanges/ChangeNotificationForm.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/store/modules/navBar.js
- frontend/src/store/modules/reportChanges.js
> Report changes Viet

- backend/src/components/user.js
- frontend/src/components/RFI/RFIDocumentUpload.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/requestChanges/ChangeFileUpload.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/mixins/fundMixing.js
- frontend/src/store/modules/ccof/facility.js
- frontend/src/store/modules/reportChanges.js
> Added change request unlock functionality

- backend/Dockerfile
> updates to node.js to include chrome

- frontend/src/components/LandingPage.vue
- frontend/src/components/requestChanges/ChangeNotificationDialogue.vue
- frontend/src/components/requestChanges/ChangeNotificationForm.vue
- frontend/src/components/requestChanges/FamilyChangeDialogueContent.vue
- frontend/src/components/requestChanges/GroupChangeDialogueContent.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/router.js
- frontend/src/utils/constants.js
> initial checking of group and family dialogue using components

- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/requestChanges/ChangeNotificationForm.vue
- frontend/src/components/requestChanges/GroupChangeDialogueContent.vue
> added change notification info form to new facility

- backend/src/components/changeRequest.js
- backend/src/routes/changeRequest.js
- backend/src/util/mapping/ChangeRequestMappings.js
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/store/modules/reportChanges.js
> CCFRI-2418 - add deleteChangeAction and update change request history table

- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
> add link to list of faclities

- backend/src/components/changeRequest.js
- frontend/src/components/requestChanges/ChangeNotificationForm.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
- frontend/src/store/modules/auth.js
- frontend/src/store/modules/navBar.js
- frontend/src/store/modules/reportChanges.js
> navbar updates for change request

- frontend/src/components/CcfriEstimator.vue
> fixed a bug where parentfee would show as zero in select a month

- frontend/src/components/ccofApplication/family/FamilyFunding.vue
> added required for entire month closure, ass per comments from ticket

- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
- frontend/src/store/modules/ccfriApp.js
> cleanup, fix next button, remove unneeded code / comments, etc

- frontend/src/components/mtfi/CurrentFeeVerification.vue
> fixing code smells

- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/mtfi/MtfiSelectFacility.vue
- frontend/src/components/summary/changeRequest/MTFISummary.vue
- frontend/src/router.js
- frontend/src/store/modules/reportChanges.js
> fix bugs in MTFI change request

- frontend/src/components/mtfi/MtfiSelectFacility.vue
- frontend/src/store/modules/reportChanges.js
- frontend/src/store/modules/summaryDeclaration.js
> fix bug CCFRI-2534 in MTFI summary dec and some enhancements

- frontend/src/components/LandingPage.vue
- frontend/src/components/mtfi/MTFIInfo.vue
- frontend/src/components/requestChanges/ChangeInformation.vue
- frontend/src/store/modules/navBar.js
> Mtfi bug fixes

- frontend/src/components/requestChanges/ChangeInformation.vue
> Fixed Change information hyperlink to open new tab

- backend/src/components/application.js
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/mtfi/MtfiSelectFacility.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
- frontend/src/mixins/organizationMixin.js
- frontend/src/store/modules/auth.js
- frontend/src/store/modules/navBar.js
- frontend/src/store/modules/summaryDeclaration.js
> Viet - Update filterNavbar, Add rules for enabling new MTFI CR, Add Update button route for MTFI Action Required

- backend/src/util/mapping/Mappings.js
- frontend/src/components/ccofApplication/family/FamilyOrganization.vue
> update address info for family

- backend/src/routes/changeRequest.js
- backend/src/routes/facility.js
> cleaned up routes

- backend/src/components/message.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/MessagesPage.vue
> added fiscal year to messages

- backend/src/components/pdf.js
- frontend/src/components/SubmissionHistory.vue
- frontend/src/utils/constants.js
> Report changes mk

- frontend/src/components/mtfi/CurrentFeeVerification.vue
> added ccfriId to currentPcfCCfri in order to get 3% median to trigger

- frontend/src/components/CcfriEstimator.vue
> hid the info banner stating we are currently updating fees

- backend/src/components/application.js
- backend/src/components/facility.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/mtfi/MtfiSelectFacility.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/components/summary/group/CCFRISummary.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/mixins/globalMixin.js
- frontend/src/store/modules/auth.js
- frontend/src/store/modules/navBar.js
- frontend/src/store/modules/summaryDeclaration.js
- frontend/src/utils/common.js
> Viet - Add facility status to backend, and update filter navbar and CR facilities

- backend/src/components/changeRequest.js
- backend/src/util/mapping/ChangeRequestMappings.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/RFI/RFIDocumentUpload.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/mtfi/MtfiSelectFacility.vue
- frontend/src/components/requestChanges/ChangeFileUpload.vue
- frontend/src/components/requestChanges/ChangeNotificationForm.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/mixins/fundMixing.js
- frontend/src/store/modules/auth.js
- frontend/src/store/modules/ccof/facility.js
- frontend/src/store/modules/navBar.js
- frontend/src/store/modules/reportChanges.js
- frontend/src/store/modules/summaryDeclaration.js
> refactored change request to not use userprofile change requests

- .github/workflows/deploy-to-openshift-backend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-prod.yml
- .github/workflows/deploy-to-openshift-frontend-test.yml
- tools/openshift/backend.dc.yaml
- tools/openshift/frontend.dc.yaml
deploying with certs via github actions
> testing deploy with certificates.

- frontend/src/components/RFI/RFIDocumentUpload.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> UAT bug tickets for release 1.9.5

- backend/src/components/pdf.js
- backend/src/components/utils.js
- backend/src/routes/pdf.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/SubmissionHistory.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/store/modules/document.js
> Bug fixes for release 195 - CCFRI-1840 and CCFRI-2847

- backend/src/components/application.js
- backend/src/components/changeRequest.js
- backend/src/util/constants.js
- frontend/src/components/LandingPage.vue
> CCFRI-2602 - Add MTFI Statuses to Landing page Facility Cards

- backend/src/components/application.js
- backend/src/components/changeRequest.js
- backend/src/components/utils.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/summary/group/ECEWESummary.vue
- frontend/src/components/summary/group/UploadedDocumentsSummary.vue
> Fix bugs for release 1.9.6

- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccofApplication/family/FamilyFunding.vue
- frontend/src/components/ccofApplication/family/FamilyOrganization.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/requestChanges/FamilyChangeDialogueContent.vue
- frontend/src/components/requestChanges/GroupChangeDialogueContent.vue
- frontend/src/store/modules/ccfriApp.js
> Bugfixes for TEST

- backend/src/components/user.js
> Change request new facility ccfri 2967

- .github/workflows/deploy-to-openshift-backend-prod.yml
- .github/workflows/deploy-to-openshift-frontend-prod.yml
- backend/src/components/application.js
- tools/openshift/backend.dc.yaml
Adding in rate limit annotations so that they will be reflected on our routes.
> adding in rate limit annotations to backend.dc.yaml

- backend/src/components/facility.js
- backend/src/routes/facility.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
- frontend/src/store/modules/ccfriApp.js
- frontend/src/store/modules/eceweApp.js
- frontend/src/store/modules/reportChanges.js
- frontend/src/utils/common.js
> Release 196 jb3 - update closure dates, prevent CR submission when PCF unlocked

- frontend/src/components/LandingPage.vue
- frontend/src/components/requestChanges/ChangeNotificationForm.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/mixins/facilityMixin.js
> Fix Back button routing for Facility Info page

- frontend/src/components/LandingPage.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/store/modules/application.js
- frontend/src/store/modules/eceweApp.js
> fix ece-we, license upload for NavBar

- frontend/src/components/NewAppIntermediatePage.vue
> updated working based on new screenshot

- backend/src/components/changeRequest.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/mtfi/MtfiSelectFacility.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/modules/application.js
- frontend/src/store/modules/ccfriApp.js
- frontend/src/store/modules/ccof/facility.js
- frontend/src/store/modules/navBar.js
- frontend/src/store/modules/reportChanges.js
> fix new application for multi fiscal, bug fixes 3015 3016, removing unneeded code

- frontend/src/components/LandingPage.vue
> fixed the pcf update button issue

- frontend/src/components/LandingPage.vue
- frontend/src/components/NewAppIntermediatePage.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccofApplication/RenewOrganization.vue
- frontend/src/components/requestChanges/ChangeInformation.vue
- frontend/src/components/summary/group/CCFRISummary.vue
- frontend/src/store/modules/application.js
- frontend/src/store/modules/ccof/facility.js
- frontend/src/store/modules/reportChanges.js
- frontend/src/utils/common.js
> Bugfixes, wording changes, update code for checking if CR active 

- frontend/package-lock.json
- frontend/public/index.html
- frontend/src/components/ccofApplication/family/FamilyFunding.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/utils/formatTime.js
- frontend/src/utils/rules.js
Bug Fixes for CCFR-1280, CCFRI-1205, CCFRI-1303
> Request to merge release 196 poornima

- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/FacilitySearch.vue
- frontend/src/components/LandingPage.vue
- frontend/src/components/Login.vue
- frontend/src/components/ccofApplication/family/Eligibility.vue
- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/store/modules/ccof/facility.js
- frontend/src/store/modules/navBar.js
- frontend/src/utils/rules.js
Bug fixes for: CCFRI-821,1183,1206,1216,1217,1664,2043,413,1122,349,350,335,377,2696
> Bugfixes/a list of MyCCS fixes ready to be merged into release-196

- frontend/src/store/modules/ccfriApp.js
> fixed a bug where RFI does not trigger immediately on a renewal

- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/mtfi/MTFIInfo.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
- frontend/src/store/modules/reportChanges.js
- frontend/src/utils/constants.js
CCFRI-3069 - update MTFI Info page - the user will not be able to create new MTFI CR if there is any Active CR (i.e.: Incomplete, Submitted, Action Required)
Update/clean up MTFI Info's routing
Disable Select Facility route in Nav Bar by default if Org type is Family.
- Bug fix (non-breaking change which fixes an issue)
> CCFRI-3069 - update MTFI Info page - the user will not be able to create new MTFI CR if there is any Active CR

- backend/Dockerfile
> updated permissions on the tmp/npm log folder

- backend/Dockerfile
> testing with updated permissions on dockerfile

- backend/Dockerfile
> updates to make tmp/npm to be writable by the pod user

- frontend/src/components/LandingPage.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/summary/group/ECEWESummary.vue
> Update Ecewe Question, BCSSEA links, heading update

- frontend/src/utils/common.js
CCFRI-2682 and CCFRI-2694 - update filterFacilityListForPCF to match with requirements in CCFRI-2682
> CCFRI-2682 and CCFRI-2694 - update filterFacilityListForPCF to match with requirements in 2682

- backend/src/components/rfiApplication.js
- backend/src/routes/application.js
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/store/modules/navBar.js
- frontend/src/utils/common.js
> Release 196 jb4

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/store/modules/navBar.js
- frontend/src/store/modules/summaryDeclaration.js
> Release 196 jb4 - updates so viewing historical CR doesn't break everything

- .github/workflows/deploy-to-openshift-backend-prod.yml
- .github/workflows/deploy-to-openshift-frontend-prod.yml
- backend/src/components/application.js
- backend/src/components/user.js
- tools/openshift/backend.dc.yaml
> Release 196 main merge

- frontend/src/components/LandingPage.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/store/modules/ccfriApp.js
> Release 196 median fee bug

- frontend/src/components/ccofApplication/RenewOrganization.vue
> load cr store on renewal page

- frontend/src/components/mtfi/MtfiSelectFacility.vue
> fixed issue where closed facility not showing up on MTFI

- backend/src/components/facility.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
- frontend/src/store/modules/ccfriApp.js
- frontend/src/store/modules/summaryDeclaration.js
> Release 196 jb5

- backend/src/components/facility.js
> added timezone to deal with date offset

- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/requestChanges/ChangeNotificationForm.vue
> unlock for change noti

- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/store/modules/application.js
> Release 196 jb6

- frontend/src/components/LandingPage.vue
> prevented new applications from being renewed if not approved

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
> Hide Funding agreement number for 2024 25 applications

- frontend/src/components/LandingPage.vue
- frontend/src/components/RFI/NMF.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/mixins/facilityMixin.js
> Release 196 jb7

- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
> Jenbeckett validation

- frontend/src/components/RFI/NMF.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/guiComponents/FacilityHeader.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/mtfi/MtfiSelectFacility.vue
…laying facility name, ID, and license. Now they all look uniform. CCFRI 3466
> Add Facility Header component 

- frontend/src/components/SummaryDeclaration.vue
> No Funding Agreement Number for Change Request

- .gitignore
- backend/src/util/mapping/Mappings.js
> Fix RFI expense decimal bug

- frontend/src/components/eceweApplication/EceweEligibility.vue
> fix: union info unavailable to non-public ECEs

- backend/src/components/application.js
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/store/modules/reportChanges.js
> fix with no formatting

- .github/workflows/codeql-analysis.yaml
- .github/workflows/deploy-to-openshift-backend-dev.yml
- .github/workflows/deploy-to-openshift-backend-prod.yml
- .github/workflows/deploy-to-openshift-backend-qa.yml
- .github/workflows/deploy-to-openshift-backend-uat.yml
- .github/workflows/deploy-to-openshift-frontend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-prod.yml
- .github/workflows/deploy-to-openshift-frontend-qa.yml
- .github/workflows/deploy-to-openshift-frontend-uat.yml
- .github/workflows/on_pr_closed.yaml
- .github/workflows/on_pr_opened.yaml
- .github/workflows/tag-create.git.and.imagestream.tag.yml
- .github/workflows/trivy-scan.yml
- .github/workflows/unit_tests.yaml
- tools/openshift/backend.dc.yaml
- tools/openshift/frontend.dc.yaml
Refactors the deployment config templates and workflows in order to support multiple environments per namespace.  Adds the QA environment.
> Add QA Workflows

- .github/workflows/deploy-to-openshift-backend-dev.yml
- .github/workflows/deploy-to-openshift-backend-prod.yml
- .github/workflows/deploy-to-openshift-backend-qa.yml
- .github/workflows/deploy-to-openshift-backend-uat.yml
- .github/workflows/deploy-to-openshift-frontend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-prod.yml
- .github/workflows/deploy-to-openshift-frontend-qa.yml
- .github/workflows/deploy-to-openshift-frontend-uat.yml
Also removes Zap from Prod, where we don't want accidental data sent
> fix: zap scans

- .github/workflows/deploy-to-openshift-backend-qa.yml
- tools/config/update-configmap.sh
- tools/openshift/backend-no-fb.dc.yaml
We don't want to muddy our index outside of app development here
> fix: remove fluenbit/splunk in QA

- tools/openshift/backend-no-fb.dc.yaml
A couple followup patches to fix a couple of volume errors in the QA workflow.
> Remove qa splunk patch

- backend/Dockerfile
- backend/src/components/application.js
> Fix puppeteer defunct chrome subprocesses

- frontend/src/components/requestChanges/ChangeNotificationForm.vue
> fix: out of date links in ChangeNotificationForm

- frontend/src/App.vue
- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/FRICalculator.vue
- frontend/src/components/Footer.vue
- frontend/src/components/Header.vue
- frontend/src/components/Login.vue
Fixed CSS issues on Homepage, Header and Footer after migration to Vuetify 3.
CSS updates
> Css issues vuetify vue3 upgrade

- frontend/src/App.vue
- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/FRICalculator.vue
- frontend/src/components/FacilitySearch.vue
- frontend/src/components/Footer.vue
- frontend/src/components/Header.vue
- frontend/src/components/Login.vue
- Fixed 'weekly care schedule': Vuetify 3 needs a value attribute
- Fixed 'Search facilities' pop windowns opening at page load: initial value set to false was missing
- Fixed various css issues
> Css issues vuetify vue3 upgrade weekly care schedule

- backend/Dockerfile
- backend/src/components/application.js
Attempting to fix a crash with the PDF printing library.
> Give Puppeteer a place to store data

- backend/Dockerfile
ref: https://github.com/puppeteer/puppeteer/issues/11023#issuecomment-1776247197
> Set XDG dirs to maybe prevent chromium crashes

- backend/Dockerfile
- backend/src/components/application.js
> Fix race condition and update docker image to current LTS

- frontend/public/styles/common.css
- frontend/src/App.vue
- frontend/src/components/LandingPage.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/guiComponents/AppDateInput.vue
- frontend/src/components/guiComponents/AppTimeInput.vue
- frontend/src/components/guiComponents/FiscalYearSlider.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/components/util/NavButton.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/mixins/organizationMixin.js
- frontend/src/store/ccfriApp.js
- frontend/src/store/ccof/facility.js
- frontend/src/store/ccof/organization.js
- frontend/src/store/eceweApp.js
- frontend/src/utils/format.js
- frontend/src/utils/rules.js
- frontend/vite.config.js
> Viet fix application vue3

- frontend/src/App.vue
- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/FRICalculator.vue
- frontend/src/components/Header.vue
- frontend/src/components/MessagesPage.vue
- frontend/src/components/util/NavBar.vue
- CCFRI-3677 MyCCS - UX/UI Application placeholder usability (text wrap)
- Fixed issues with 'Message' feature
- Fixed issues on the NavBar menu
> Ccof vue 3 update ccof apply

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/summary/group/CCFRISummary.vue
- frontend/src/components/summary/group/CCOFSummary.vue
- frontend/src/components/summary/group/FacilityInformationSummary.vue
- frontend/src/components/summary/group/OrganizationSummary.vue
- frontend/src/store/summaryDeclaration.js
Application Form - Fixed errors on Summary Declaration page.
Errors caused by Vue/Vuetify 3 upgrade and usage of Pinia in various components.
> Ccof vue 3 upgrade summary declaration

- frontend/src/components/summary/group/FacilityInformationSummary.vue
CCFRI-2153 - MyCCS - Application Summary text wrap
https://eccbc.atlassian.net/jira/software/c/projects/CCFRI/boards/34?selectedIssue=CCFRI-2153
> Ccfri 2153

- frontend/package.json
> Add vite to package json frontend

- frontend/src/App.vue
> Fix for the environment toolbar

- backend/src/util/mapping/Mappings.js
> Remove unused mappings for value that is being removed from CRM

- frontend/src/App.vue
- frontend/src/components/Footer.vue
- frontend/src/components/Header.vue
- frontend/src/components/Login.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/TheEnvBar.vue
- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/guiComponents/AppDateInput.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
- frontend/src/store/app.js
- frontend/src/store/summaryDeclaration.js
> CCFRI-3634 and CCFRI-3713 - navbar enhancement, ELCCA update

- frontend/src/store/summaryDeclaration.js
> bug fix - unable  load declaration to submit application

- backend/src/components/application.js
- backend/src/util/browser.js
- frontend/src/App.vue
- frontend/src/components/Footer.vue
- frontend/src/components/Header.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/TheEnvBar.vue
Jira: CCOF-3694
More details in the commits.
> Allow simultaneous PDFs to be generated at once

- frontend/src/components/guiComponents/AppDateInput.vue
- frontend/src/components/guiComponents/AppTimeInput.vue
> Minor css change to move icon to the start of AppDateInput and AppTimeInput

- frontend/src/components/LandingPage.vue
- frontend/src/components/guiComponents/LargeCard.vue
- frontend/src/components/guiComponents/SmallCard.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/store/application.js
- frontend/src/store/auth.js
- frontend/src/store/message.js
- frontend/src/store/navBar.js
- Fix layout issues on landing page including bullet position and html formatting
- Remove some console logs
- Cleanup component warnings
> CCFRI-3810 - Landing page html

- frontend/src/components/eceweApplication/EceweEligibility.vue
> updated a link

- frontend/src/components/LandingPage.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/util/NavBar.vue
> CCCFRI-3632, CCFRI-3678, CCFRI-3820 - bug fix and add facilityId to Licence Upload and NavBar

- frontend/src/components/summary/group/CCFRISummary.vue
Removed duplicate Opt-Out text and updated from method to computed.
> CCFRI-3877 - Opt-Out repeated for CCFRI

- backend/src/components/message.js
- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/LandingPage.vue
- frontend/src/components/MessagesPage.vue
- frontend/src/components/RFI/NMF.vue
- frontend/src/components/SubmissionHistory.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccofApplication/RenewOrganization.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/mtfi/MTFIInfo.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/components/summary/group/NMFSummary.vue
- frontend/src/router.js
- frontend/src/store/app.js
- frontend/src/store/application.js
- frontend/src/utils/format.js
- frontend/tests/unit/store/ccfriApp.spec.js
> ccfri-3832 - update fiscal year label

- frontend/src/components/summary/group/CCOFSummary.vue
bug - ccfri 3822 - Preschool sessions not displaying on the Summary Dec
> updates to CCOF summary dec - 

- frontend/src/utils/format.js
> ccfri-3894 - update formatFiscalYearName function

- backend/src/components/application.js
- backend/src/routes/application.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/LandingPage.vue
- frontend/src/components/ccfriApplication/AFS/ApprovableFeeSchedule.vue
- frontend/src/components/ccfriApplication/AFS/ApprovableParentFeesCards.vue
- frontend/src/components/ccofApplication/family/Eligibility.vue
- frontend/src/components/guiComponents/FacilityHeader.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/router.js
- frontend/src/store/app.js
- frontend/src/store/application.js
- frontend/src/store/ccfriApp.js
- frontend/src/utils/common.js
- frontend/src/utils/constants.js
> ccfri-3752, ccfri-3754, ccfri-3813 - add AFS page to Application

- backend/src/components/application.js
> save fees CCFRI

- frontend/src/components/CancelApplicationDialog.vue
- frontend/src/components/LandingPage.vue
- frontend/src/components/guiComponents/AppButton.vue
- frontend/src/components/guiComponents/AppDialog.vue
- frontend/src/store/application.js
> CCFRI-3809 - cancel application bug fix

- .github/workflows/deploy-to-openshift-backend-dev.yml
- .github/workflows/deploy-to-openshift-backend-prod.yml
- .github/workflows/deploy-to-openshift-backend-qa.yml
- .github/workflows/deploy-to-openshift-backend-uat.yml
- .github/workflows/deploy-to-openshift-frontend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-prod.yml
- .github/workflows/deploy-to-openshift-frontend-qa.yml
- .github/workflows/deploy-to-openshift-frontend-uat.yml
- .github/workflows/deploy-to-openshift-nginx-dev.yml
- .github/workflows/tag-create.git.and.imagestream.tag.yml
- tools/config/update-configmap.sh
- tools/openshift/backend.deployment.yaml
- tools/openshift/backend.no-fb.deployment.yaml
- tools/openshift/frontend.deployment.yaml
- tools/openshift/nginx.deployment.yaml
In this PR we:
1. Convert the DeploymentConfigs to Deployments
2. Implement Infrastructure as Code for our Nginx implementation
3. Switch out using the "most recent tag" in favor of just entering an explicit release tag
> Migrate to Deployments and More

- frontend/src/components/CcfriEstimator.vue
> ccfri-3989 - ccfri estimator vue 3 bug fix

- frontend/src/components/CCFRIApplicationForm.vue
- frontend/src/components/CcfriEstimator.vue
- frontend/src/components/LandingPage.vue
- frontend/src/components/RFI/NMF.vue
- frontend/src/components/RFI/RFIDocumentUpload.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/CcfriEceLanding.vue
- frontend/src/components/ccofApplication/RenewOrganization.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/summary/group/RFISummary.vue
- frontend/src/components/util/NavBar.vue
Ccfri 3895 language updates
https://eccbc.atlassian.net/browse/CCFRI-3895
> Ccfri 3895 language updates

- backend/src/components/application.js
> Ccfri prod save parent fees

- backend/src/app.js
- backend/src/components/application.js
- backend/src/components/document.js
- backend/src/routes/application.js
- backend/src/routes/document.js
- backend/src/util/mapping/Mappings.js
- frontend/package-lock.json
- frontend/package.json
- frontend/public/styles/common.css
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccfriApplication/AFS/AfsDecisionCard.vue
- frontend/src/components/ccfriApplication/AFS/ApprovableFeeSchedule.vue
- frontend/src/components/summary/group/AFSSummary.vue
- frontend/src/components/util/AppDocumentUpload.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/services/documentService.js
- frontend/src/store/application.js
- frontend/src/store/ccfriApp.js
- frontend/src/store/navBar.js
- frontend/src/store/summaryDeclaration.js
- frontend/src/utils/constants.js
CCFRI-3756
CCFRI-3795
CCFRI-3808
CCFRI-3987
> CCFRI-3756 - finishing AFS pages

- .github/workflows/deploy-to-openshift-backend-efx.yml
- .github/workflows/deploy-to-openshift-backend-prod.yml
- .github/workflows/deploy-to-openshift-backend-qa.yml
- .github/workflows/deploy-to-openshift-backend-uat.yml
- .github/workflows/deploy-to-openshift-frontend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-efx.yml
- .github/workflows/deploy-to-openshift-frontend-prod.yml
- .github/workflows/deploy-to-openshift-frontend-qa.yml
- .github/workflows/deploy-to-openshift-nginx-dev.yml
- .github/workflows/tag-create.git.and.imagestream.tag.yml
- tools/config/update-configmap.sh
- tools/openshift/backend.deployment.yaml
- tools/openshift/backend.no-fb.deployment.yaml
- tools/openshift/frontend.deployment.yaml
- tools/openshift/nginx.deployment.yaml
Catches the release branch used for EFX up to date with main in terms of deployment flows.  This brings:
1. IaC
2. Deployments over deprecated dcs
3. The EFX env flow itself
> Release 2.1 deployment updates

- backend/src/components/application.js
- backend/src/components/changeRequest.js
- backend/src/components/lookup.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweEligibilityQuestions.vue
- frontend/src/components/eceweApplication/EceweFacilities.vue
- frontend/src/components/guiComponents/AppAlertBanner.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/components/summary/group/ECEWESummary.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/store/app.js
- frontend/src/store/eceweApp.js
- frontend/src/store/summaryDeclaration.js
- frontend/src/utils/constants.js
Also includes [CCFRI-3913](https://eccbc.atlassian.net/browse/CCFRI-3913)
-which is the ticket that adds the union status to the Summary Declaration page
backend/changeRequest.js did NOT change - I formatted it by accident when trying to add code for CR new facility
Pulled Ecewe questions into their own component to make things a little cleaner 
New questions for 2025/26 added and also tested existing functionality for 2024/25
lots of code cleanup -
CR new facility is waiting on something for CRM so that will come in a later ticket 
--Nov 28th -- update 
I found a small bug where the navBar checkmark updates the checkbox when the union question has not been completed. 
This is not a straightforward fix but I'm looking at it now. 
The Summary Declaration page WILL catch the error and …
> Ccfri 3818 ecewe group update

- backend/src/components/document.js
- backend/src/routes/document.js
- frontend/public/styles/common.css
- frontend/src/components/LandingPage.vue
- frontend/src/components/ccfriApplication/AFS/ApprovableFeeSchedule.vue
- frontend/src/components/requestChanges/ChangeFileUpload.vue
- frontend/src/components/requestChanges/ChangeInformation.vue
- frontend/src/components/requestChanges/ChangeNotificationDialogue.vue
- frontend/src/components/requestChanges/ChangeNotificationForm.vue
- frontend/src/components/requestChanges/FamilyChangeDialogueContent.vue
- frontend/src/components/requestChanges/GroupChangeDialogueContent.vue
- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
- frontend/src/components/summary/changeRequest/ChangeNotificationFormSummary.vue
- frontend/src/components/util/AppDocumentUpload.vue
- frontend/src/services/documentService.js
- frontend/src/store/reportChanges.js
- frontend/src/utils/constants.js
> CCFRI-3971 - Change Notification Form document upload bug fix

- backend/src/util/mapping/ChangeRequestMappings.js
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/eceweApplication/EceweEligibilityQuestions.vue
- frontend/src/store/eceweApp.js
the file ChangeRequestMapping looks like a big change - but it's mostly just formatting. The only two additions are for the new fields for CR New Facility and the new questions for 2025/26
> fixed CR new facility so it works with the new ecewe questions

- backend/src/components/supportingDocumentUpload.js
- backend/src/routes/supportingDocuments.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/RFI/RFIDocumentUpload.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/ccofApplication/group/LicenseUpload.vue
- frontend/src/components/requestChanges/ChangeFileUpload.vue
- frontend/src/components/summary/group/UploadedDocumentsSummary.vue
- frontend/src/components/util/AppDocumentUpload.vue
- frontend/src/store/application.js
- frontend/src/store/summaryDeclaration.js
- frontend/src/store/supportingDocumentUpload.js
- frontend/src/utils/common.js
- frontend/src/utils/constants.js
- frontend/src/utils/file.js
- frontend/src/utils/rules.js
> ccfri-4027 - fix document upload bugs and code refactor

- frontend/public/styles/common.css
- frontend/src/components/Login.vue
- frontend/src/components/MinistryLogin.vue
Added classes to override Vuetify text-h4/text-h5 classes.
Removed styles no longer needed.
> CCFRI-4047 - Wrong header font

- backend/src/components/application.js
- backend/src/components/rfiApplication.js
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/eceweApplication/EceweEligibility.vue
- frontend/src/components/mtfi/MTFIInfo.vue
- frontend/src/components/summary/group/ECEWESummary.vue
- frontend/src/store/summaryDeclaration.js
bugs 
https://eccbc.atlassian.net/browse/CCFRI-4209
https://eccbc.atlassian.net/browse/CCFRI-4173
https://eccbc.atlassian.net/browse/CCFRI-4095
and coming in shortly 
https://eccbc.atlassian.net/browse/CCFRI-3850
> Bugfixes CCFRI 4209 4173 4095 3850

- frontend/src/components/MessagesPage.vue
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/services/documentService.js
> ccfri-4049 - fix Vue3 bugs for Message UI

- frontend/src/components/RFI/NMF.vue
- frontend/src/components/summary/group/NMFSummary.vue
> ccfri-4050 - NMF bug fixes

- frontend/src/components/ccofApplication/CcofApplicationTypeSelector.vue
- frontend/src/components/guiComponents/LargeCard.vue
- frontend/src/components/summary/group/CCOFSummary.vue
- frontend/src/components/summary/group/CCOFSummaryFamily.vue
> CCFRI-4222, CCFRI-4228 - fix summary declaration bug and update urls for form pdf

- frontend/src/components/Header.vue
- frontend/src/components/Impersonate.vue
- frontend/src/components/MinistryLogin.vue
> Vue 3 UI bug fixes - Headers and Impersonate

- frontend/src/components/LandingPage.vue
- frontend/src/components/ccofApplication/family/FamilyFunding.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/components/summary/group/FacilityInformationSummary.vue
- frontend/src/components/summary/group/OrganizationSummary.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/mixins/organizationMixin.js
- frontend/src/store/ccof/facility.js
- frontend/src/store/ccof/funding.js
- frontend/src/store/navBar.js
> Ccfri 4004 UI bugs

- frontend/src/components/LandingPage.vue
- frontend/src/components/ccofApplication/family/FamilyFunding.vue
- frontend/src/components/ccofApplication/group/FundAmount.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/requestChanges/ReportChanges.vue
- frontend/src/components/summary/group/FacilityInformationSummary.vue
- frontend/src/components/summary/group/OrganizationSummary.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/mixins/organizationMixin.js
- frontend/src/store/ccof/facility.js
- frontend/src/store/ccof/funding.js
- frontend/src/store/navBar.js
Fix so that some Org Information does not get cut off on the summary Dec page. I also added a max char length for the affected fields so it will not run over. Quick google says these fields are generally 40 chars so I made it 60 to be safe. 
Other fixes:
https://eccbc.atlassian.net/browse/CCFRI-4270
Update checkboxes on Family / Group CCOF pages to use the values 1 and 0 and not default to Boolean values. This will let the checkboxes populate correctly after saving then refreshing.
Landing page had an error with an old LoDash import. This error was preventing some facilities with MTFI from loading properly.
Action Required text on Report Changes page used to be red. Due to the vue3 update to the data-table, it was not rendering properly. 
I made a bug ticket for this: …
> ccfri 4004, and other small ui bug fixes

- frontend/src/components/LandingPage.vue
> Ccfri 4264 facility landing page cards

- backend/src/util/constants.js
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/summary/group/ECEWESummary.vue
- frontend/src/components/summary/group/FacilityInformationSummary.vue
- frontend/src/store/summaryDeclaration.js
CCFRI 3912 Re-order ECEWE sections 
CCFRI 4307 ECEWE mapping codes incorrect
> Ccfri 3912 ecewe sections

- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> Ccfri 4247 fix closure table

- frontend/src/components/summary/changeRequest/MTFISummary.vue
- frontend/src/components/summary/group/CCFRISummary.vue
> Text to summary mtfi

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
> PROD hotfix

- backend/src/components/application.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/store/ccfriApp.js
> Ccfri 4457 reset afs status for MTFI

- frontend/src/components/SummaryDeclaration.vue
> CCFRI 4483 - fix panel expansion on summary declaration

- backend/src/components/lookup.js
- backend/src/util/constants.js
- frontend/src/components/guiComponents/LargeCard.vue
- frontend/src/store/app.js
- frontend/src/store/ccof/organization.js
> Ccfri 4431 10 program years

- .github/workflows/deploy-to-openshift-backend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-dev.yml
Version 0.8.0 no longer in artifactory
> fix: outdated zap scan versions

- backend/src/components/application.js
> CCFRI 4381 more logs for PDF gen

- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
> Ccfri 4381 pdf generation - fix checkbox not loading on CR summary dec printable version

- backend/src/components/application.js
- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
> Ccfri 4381 pdf generation wait for content to appear

- backend/package-lock.json
- backend/package.json
- backend/src/components/application.js
- backend/src/components/facility.js
- backend/src/components/nmfApplication.js
- backend/src/components/rfiApplication.js
- backend/src/routes/application.js
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/store/summaryDeclaration.js
This doubles the speed by which we can load data in parallel and offloads the task from Chrome.
Note: The data, when on a YMCA scale is still too much for the front end to render at once.  This is an incremental update.
> Migrate data load to nodeJS backend

- backend/src/components/changeRequest.js
- backend/src/components/facility.js
- backend/src/util/mapping/MappableObject.js
Remove unnecessary backend console.log. All logging should be done with a logger to better control levels.
Code cleanup.
> Backend console cleanup

- .github/workflows/deploy-to-openshift-backend-dev.yml
- backend/package-lock.json
- backend/package.json
- backend/src/app.js
- backend/src/components/canadaPost.js
- backend/src/components/facility.js
- backend/src/config/index.js
- backend/src/routes/canadaPost.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/ccofApplication/family/FamilyOrganization.vue
- frontend/src/components/ccofApplication/group/FacilityInformation.vue
- frontend/src/components/ccofApplication/group/OrganizationInformation.vue
- frontend/src/components/guiComponents/AppAddressForm.vue
- frontend/src/components/guiComponents/AppAddressLookup.vue
- frontend/src/mixins/facilityMixin.js
- frontend/src/mixins/organizationMixin.js
- frontend/src/services/canadaPostService.js
- frontend/src/utils/constants.js
- frontend/src/utils/rules.js
- tools/config/update-configmap.sh
> CCFRI-4492 - implement Canada Post AddressComplete API

- .github/workflows/deploy-to-openshift-backend-prod.yml
Also in main via https://github.com/bcgov/EDUC-CCOF/pull/646
> feat: increase pods and max cpu for Node backend

- .github/workflows/deploy-to-openshift-backend-efx.yml
- .github/workflows/deploy-to-openshift-backend-prod.yml
- .github/workflows/deploy-to-openshift-backend-qa.yml
- .github/workflows/deploy-to-openshift-backend-uat.yml
> Added Canada Post secrets to upper environments.

- frontend/src/components/SubmissionHistory.vue
fix for https://eccbc.atlassian.net/browse/CCFRI-4578. Added pagination and sorting by submission date on Submission History page
> added pagination and sorting

- frontend/public/js/config/config.js
- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/SupportingDocumentUpload.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/navBar.js
- tools/openshift/frontend.deployment.yaml
> remove Dec B bypass code

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
- frontend/src/components/summary/changeRequest/ChangeNotificationFormSummary.vue
- frontend/src/components/summary/group/CCOFSummary.vue
- frontend/src/components/summary/group/CCOFSummaryFamily.vue
- frontend/src/components/summary/group/FacilityInformationSummary.vue
- frontend/src/components/summary/group/NMFSummary.vue
- frontend/src/components/summary/group/OrganizationSummary.vue
- frontend/src/components/summary/group/RFISummary.vue
- frontend/src/components/summary/group/UploadedDocumentsSummary.vue
- frontend/src/store/summaryDeclaration.js
> Update declaration validations

- frontend/src/components/ccfriApplication/AFS/ApprovableFeeSchedule.vue
- frontend/src/components/summary/group/AFSSummary.vue
- frontend/src/components/summary/group/CCOFSummary.vue
- frontend/src/store/application.js
> ccfri-4450 - fix CCOF summary validation

- frontend/src/components/ccfriApplication/AFS/ApprovableFeeSchedule.vue
- frontend/src/store/application.js
> ccfri-4677 - bug fix for Application AFS - unable to remove uploaded document

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
- frontend/src/components/summary/group/AFSSummary.vue
> CCFRI-4677 - Fix AFS summary validation bug

- tools/config/update-configmap.sh
Address potential environment inconsistencies in restarts.
> fix: set env with new configmap before restart

- frontend/src/components/ccfriApplication/group/AddNewFees.vue
> fix rfi page getting deleted bug

- frontend/src/utils/rules.js
> CCFRI-4682 - Fix file upload validation

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/summary/group/ECEWESummary.vue
- frontend/src/components/summary/group/FacilityInformationSummary.vue
- frontend/src/components/util/FacilityInformationSummaryDialog.vue
- frontend/src/services/applicationService.js
- frontend/src/store/summaryDeclaration.js
> ccfri-4641 - fix renewal summary

- frontend/src/components/applicationTemplates/v1/group/summary/OrganizationSummary.vue
- frontend/src/components/applicationTemplates/v2/group/summary/CCOFSummary.vue
- frontend/src/components/applicationTemplates/v2/group/summary/FacilityInformationSummary.vue
- frontend/src/components/applicationTemplates/v2/group/summary/OrganizationSummary.vue
- frontend/src/services/applicationService.js
- frontend/src/utils/rules.js
- frontend/src/utils/validation.js
> CCFRI-4641 - add missing validations for summary

- backend/src/util/mapping/Mappings.js
- frontend/src/components/ClosureDetailsDialog.vue
- frontend/src/components/OrganizationClosures.vue
- frontend/src/utils/constants.js
Implemented the "View Details" button on the Organization Closures page allowing users to view additional details about a selected closure.
New feature (non-breaking change which adds functionality)
> Ccfri 4839   closure details dialog

- frontend/src/components/NewClosureRequestDialog.vue
Fixing a build issue due to misspelt import.
> ccfri 4764 - Fixed issue with auth.js import

- frontend/src/components/CcfriEstimator.vue
This PR hopefully improves the styles of the month selector, makes it more useful on mobile, and more fluid on desktop.
Jira: CCFRI-2293
> Improve month selector

- backend/src/components/changeRequest.js
- frontend/src/components/NewClosureRequestDialog.vue
- frontend/src/components/closure/ClosureChangeRequestDialog.vue
Update the Change Request statuses to Submitted following successful creation of all necessary entitites
> Ccfri-4969-set-New-Closure-Change-Request-Status-to-Submitted

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/applicationTemplates/v1/group/summary/CCFRISummary.vue
- frontend/src/components/applicationTemplates/v2/group/CCOF/OrganizationInformation.vue
- frontend/src/components/applicationTemplates/v2/group/summary/CCFRISummary.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
- frontend/src/components/summary/changeRequest/MTFISummary.vue
- frontend/src/components/util/ApplicationClosureCard.vue
- frontend/src/mixins/ccfriMixin.js
- frontend/src/mixins/summaryMixin.js
- frontend/src/services/applicationService.js
- frontend/src/utils/constants.js
CCFRI-4994 - Remove org info and facility info validation from renewal application summary
CCFRI-4950, 4931 - Fix CCFRI and MTFI fees validation in summary
CCFRI-4636 - set fullClosure to TRUE by default for application template 2
> CCFRI-4931, CCFRI-4950, CCFRI-4994 - Application summary bug fixes

- frontend/package.json
- frontend/src/components/FacilitySearch.vue
- frontend/src/components/MsieBanner.vue
- frontend/src/components/RFI/RFILanding.vue
- frontend/src/components/mtfi/CurrentFeeVerification.vue
CCOF frontend:  resolved 3 issues while the frontend is running.
Fix 3 CCOF issues in the frontend.
1) Vite warning
2) Invalid html
3) Deep selectors
> CCOF frontend:  resolved 3 issues while the frontend is running.

- backend/src/components/application.js
CCFRI-5019: task is completed.
Remove Change Request of the type Closure from the change request history table.
New feature (non-breaking change which adds functionality) 
Documentation (non-breaking change with enhancements to documentation)
> CCFRI-5019: task is completed.

- frontend/src/components/LandingPage.vue
- frontend/src/components/accountMgmt/ManageUsers.vue
- frontend/src/router.js
- frontend/src/utils/constants.js
CCFRI-4968: task is completed.
- Update to Home Page to add navigation to Manage Users
- The navigation in Home Page is updated as 3 columns to display menu card items in each row.
- Empty component is initially committed for Manage Users
> CCFRI-4968: task is completed.

- frontend/public/styles/common.css
- frontend/src/components/RFI/NMF.vue
- frontend/src/components/applicationTemplates/v2/group/CCOF/OrganizationInformation.vue
- frontend/src/components/summary/group/NMFSummary.vue
- frontend/src/components/summary/group/RFISummary.vue
- frontend/src/store/summaryDeclaration.js
CCFRI-4907 - update section headers for RFI and NMF summary
CCFRI-4870 - display NMF comment question labels in summary, and some code clean up
CCFRI-5150 - update tooltip text for Incorporation Number field
> CCFRI-4870, CCFRI-4907, CCFRI-5150 - RFI and NMF Summary UI updates

- frontend/src/components/ccofApplication/group/ApplicationConfirmation.vue
- frontend/src/components/util/NavBar.vue
- frontend/src/store/application.js
- CCFRI-5020 - only enable Add Facility, Licence Upload, CCFRI, ECEWE once the provider has successfully added at least 1 facility.
- Remove a redundant field in application store
> CCFRI-5020 - Start application bug fix

- frontend/src/components/summary/group/NMFSummary.vue
- frontend/src/components/util/FacilityInformationSummaryCard.vue
- frontend/src/components/util/FacilityInformationSummaryDialogHeader.vue
- frontend/src/mixins/summaryMixin.js
- frontend/src/store/summaryDeclaration.js
- CCFRI-5148 - Add health authority to Facility info summary
- CCFRI-5174 - update title of NMF summary
> CCFRI-5148, CCFRI-5174 - Application Summary update - facility info, NMF

- frontend/src/components/SummaryDeclaration.vue
- frontend/src/components/requestChanges/SummaryDeclarationChangeRequest.vue
Validate and fix usage of enrol/enrolled/enrollment.
Fixed two issues in Dec B.
> CCFRI-5176 - Verify Enrol usage

- .github/workflows/create-redis-cluster-dev.yml
- tools/openshift/redis-ha.yaml
- tools/redis/Dockerfile
This PR adds the Redis "High Availability" setup as a github workflow in DEV. This is a work in progress.
> Add redis GH workflow

- frontend/src/components/SubmissionHistory.vue
- frontend/src/utils/format.js
Added a new function in format.js to convert the date to local time zone date
>  Added a new function to convert date to local timezone date

- backend/src/config/index.js
Missed server config for new properties.
Added entries to index.js.
> Added missing config.

- frontend/public/styles/common.css
- frontend/src/components/fundingAgreements/ManageFundingAgreements.vue
- frontend/src/utils/constants.js
- frontend/src/utils/format.js
Implementation of dropdown instead of checkboxes
Highlighting for status
Update buttons
> Funding Agreement Summary View changes

- backend/src/app.js
- backend/src/components/contact.js
- backend/src/routes/contact.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/accountMgmt/ManageUsers.vue
- frontend/src/components/guiComponents/AppButton.vue
- frontend/src/services/contactService.js
- frontend/src/utils/constants.js
> feat: manage users data table and related plumbing

- frontend/src/components/applicationTemplates/v1/group/CCOF/FundAmount.vue
- frontend/src/components/applicationTemplates/v2/group/CCOF/FundAmount.vue
- frontend/src/components/applicationTemplates/v2/group/summary/CCOFSummary.vue
- frontend/src/services/applicationService.js
CCFRI-5404 - fix application issue with saving CCOF school property label and display it in summary
> CCFRI-5404 - fix application issue with CCOF school property label

- frontend/public/styles/common.css
- frontend/src/components/fundingAgreements/ManageFundingAgreements.vue
1>. Status Highlighting:
Drafted – Provider Action Required (FFD180)
Drafted – with Ministry (E0E0E0)
2>. Spelling correcting -Licence
> Added status higlighting and spelling correction

- backend/src/components/fundingAgreement.js
- frontend/src/components/fundingAgreements/ManageFundingAgreements.vue
- frontend/src/utils/constants.js
* Removed Status= 'Drafted'' from the FA list
> removed status-drafted from fa list

- frontend/src/components/fundingAgreements/ManageFundingAgreements.vue
Removed ' FY' from funding agreement column record and dropdown
> ccfri-5573 removed FY from the dropdown and column records

- backend/src/components/fundingAgreement.js
- backend/src/routes/fundingAgreement.js
- frontend/src/components/fundingAgreements/ManageFundingAgreements.vue
- frontend/src/services/fundingAgreementService.js
> ccfri 5417: download funding agreement PDF

- frontend/src/components/applicationTemplates/v1/CCFRI/AddNewFees.vue
- frontend/src/components/applicationTemplates/v2/CCFRI/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/AddNewFees.vue
- frontend/src/components/ccfriApplication/group/ExistingFacilityFees.vue
- frontend/src/components/summary/group/RFISummary.vue
- frontend/src/mixins/ccfriMixin.js
- frontend/src/services/applicationService.js
CCFRI-5579 - UI enhancement for ExistingFacilityFee and bug fix for existingFeeCorrect question
CCFRI-5578 - RFI Summary validation bug fix and minor UI enhancement
> CCFRI-5578, 5579 - Application CCFRI-RFI bug fixes

- backend/src/components/facility.js
- backend/src/components/funding.js
- frontend/src/components/applicationTemplates/v1/family/FamilyFunding.vue
- frontend/src/components/applicationTemplates/v2/family/FamilyFunding.vue
- frontend/src/components/applicationTemplates/v2/family/FamilyFundingSummary.vue
- frontend/src/mixins/fundMixin.js
- frontend/src/services/applicationService.js
- frontend/src/store/ccof/funding.js
The Facility Licence Type uses different field names in the form and the summary. Added a fallback in ApplicationService to retrieve the correct value
> CCFRI-5713 - fix Family Funding bug - unable to click Next on Licence page

- backend/src/components/fundingAgreement.js
- backend/src/routes/fundingAgreement.js
- backend/src/util/mapping/Mappings.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/fundingAgreements/ManageFundingAgreements.vue
- frontend/src/components/fundingAgreements/ViewFundingAgreement.vue
- frontend/src/components/fundingAgreements/ViewFundingAgreements.vue
- frontend/src/components/guiComponents/AppPDFViewer.vue
- frontend/src/router.js
- frontend/src/services/fundingAgreementService.js
- frontend/src/utils/constants.js
> Ccfri 5369 spike sign in page for fa

- backend/src/util/mapping/Mappings.js
- frontend/src/components/enrolmentReports/EnrolmentReportDeclaration.vue
- frontend/src/components/enrolmentReports/SubmitConfirmationDialog.vue
- frontend/src/utils/constants.js
CCFRI-5046 - Submit Enrolment Report
> CCFRI-5046 - Submit Enrolment Report

- frontend/src/utils/common.js
Add a null check to validationHourDifference function
> Add a null check to validationHourDifference function

- backend/src/routes/facility.js
- frontend/public/styles/common.css
- frontend/src/components/orgFacilities/ManageFacility.vue
- frontend/src/components/orgFacilities/ManageFacilityDetails.vue
- frontend/src/components/orgFacilities/ManageOrganization.vue
- frontend/src/services/facilityService.js
> Add ability to update phone number and email address for facilities

- backend/src/components/facility.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/orgFacilities/ManageFacilities.vue
- frontend/src/components/orgFacilities/ManageFacility.vue
- frontend/src/utils/facility.js
> Add change request button to ManageFacility view.

- backend/src/components/contact.js
- backend/src/util/mapping/Mappings.js
Updated portal users logical name
> ccfri 6045 updated the logical name for portal roles

- backend/src/components/enrolmentReport.js
- frontend/src/components/enrolmentReports/EnrolmentReportForm.vue
- frontend/src/utils/format.js
CCFRI-5986 – Format calculated fields as currency values
CCFRI-6004 – Display all CCFRI-related fields as "--" when CCFRI Rates are empty (Not Approved / Opt-out)
> CCFRI-5986, CCFRI-6004 - update display format of ER Rates and Calculated fields

- backend/src/components/user.js
Fixed attribute name and added support for Facility Admin - Basic
- Wrong property was being checked so facilities weren't being sent to frontend.
- Added facilities to Facility Admin - Basic
> CCFRI-5956 - Fixed attribute name and added support for Facility Admin - Basic

- frontend/src/components/enrolmentReports/EnrolmentReportForm.vue
CCFRI-5986 - update ER Rates to currency format
> CCFRI-5986 - update ER Rates to currency format

- backend/src/components/contact.js
- frontend/src/components/accountMgmt/ManageUsers.vue
> feat: facilties for fac admins in manage users

- backend/src/util/mapping/Mappings.js
- frontend/src/components/enrolmentReports/EnrolmentReportForm.vue
- frontend/src/components/enrolmentReports/FullMonthClosureConfirmationDialog.vue
- frontend/src/components/guiComponents/AppDialog.vue
CCFRI-5969 - ER Full Month Closure
CCFRI-6171 - Update ER Approved Parent Fees to currency format
Add a min-height to AppDialog's title to prevent the header from collapsing during loading states.
> CCFRI-5969, CCFRI-6171 - ER Full Month Closure
